# Licensed under the Apache License, Version 2.0.

[package]
name = "polkachat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
futures = "0.3.26"

thiserror = "1.0.31"
log = "0.4.17"

tokio = {version="1.25.0", features=["rt-multi-thread"]}
http = "0.2.8"
jsonrpsee-core = "0.16.2"
jsonrpsee-client-transport = "0.16.2"
subxt = "0.25.0"
scale-info = "2.3.0"
sp-weights = "5.0.0"
parity-scale-codec = "3.2.1"
pallet-contracts-primitives = "8.0.0"

#tesseract = { path = "../../Tesseract.rs/tesseract", features = ["service"] }
#tesseract-protocol-test = { path = "../../Tesseract.rs/protocols/test", features = ["service"] }
tesseract = {git = "https://github.com/tesseract-one/Tesseract.rs", branch="master", features=["client"]}
tesseract-protocol-substrate = {git = "https://github.com/tesseract-one/Tesseract.rs", branch="master", features=["client"]}

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.20.0"
jni_fn = "0.1.0"

android_logger = "0.13.0"
log-panics = "2.1.0"

interop_android = { path = "../../Tesseract.android/rust/interop" }
tesseract_ipc_android = { path = "../../Tesseract.android/rust/ipc", features = ["client"] }

[target.'cfg(target_os = "ios")'.dependencies]
stderrlog = "0.5.4"

tesseract_utils = { git = "https://github.com/tesseract-one/Tesseract.swift", branch = "master" }
tesseract_client = { git = "https://github.com/tesseract-one/Tesseract.swift", branch = "master" }

[build-dependencies]
cbindgen = "0.24"

[lib]
crate_type = ["cdylib", "staticlib"]
